version: '3.8'

services:
  market-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market_dashboard
    volumes:
      - ${BASE_DIR}/Dashboard/data:/app/data
      - ${BASE_DIR}/config:/app/config
    environment:
      - TZ=America/Mexico_City
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NUMBA_DISABLE_JIT=1
    user: "${PUID:-1000}:${PGID:-1000}"
    restart: no

  u2-screener-runner:
    build:
      context: .
      dockerfile: Dockerfile.screener
    container_name: u2_screener_runner
    environment:
      - TZ=America/Mexico_City
      - U2_CONFIG_PATH=/app/config/u2_screener_config.json
      - U2_DISCORD_WEBHOOK_URL=${U2_DISCORD_WEBHOOK_URL}
      - U2_TELEGRAM_TOKEN=${U2_TELEGRAM_TOKEN}
      - U2_TELEGRAM_CHAT_ID=${U2_TELEGRAM_CHAT_ID}
      - NUMBA_DISABLE_JIT=1
#    user: "${PUID:-1000}:${PGID:-1000}"
    volumes:
      - ${BASE_DIR}/Screener/out:/app/out
      - ${BASE_DIR}/Screener/data:/app/data
      - ${BASE_DIR}/Screener/state:/app/state
      - ${BASE_DIR}/config/u2_screener_config.json:/app/config/u2_screener_config.json:ro
    restart: unless-stopped

  u2-screener-web:
    image: nginx:alpine
    container_name: u2_screener_web
    volumes:
      - ${BASE_DIR}/Screener/out:/usr/share/nginx/html:ro
    ports:
      - "${U2_WEB_PORT:-8088}:80"
    user: "${PUID:-1000}:${PGID:-1000}"
    restart: unless-stopped
