version: '3.8'

services:
  market-dashboard:
    build: .
    container_name: market_dashboard
    volumes:
      - /mnt/MyPool/Data/Markets/data:/app/data
      - /mnt/MyPool/Data/Markets/config:/app/config
    environment:
      - TZ=America/Mexico_City
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    restart: no
